api_platform:
  title: Hello API Platform
  version: 1.0.0
  mercure:
    include_type: true
  defaults:
    pagination_client_items_per_page: true
    collection:
      pagination:
        items_per_page_parameter_name: itemsPerPage
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

