api_platform:
  title: Hello API Platform
  version: 1.0.0
  mercure:
    include_type: true
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header